#
# Makefile for the touchscreen drivers.
#
obj-$(CONFIG_TOUCHPANEL_OPLUS) += util_interface/
obj-$(CONFIG_TOUCHPANEL_OPLUS) += touchpanel_common_driver.o touchpanel_prevention.o touchpanel_healthinfo.o
obj-$(CONFIG_TOUCHPANEL_ALGORITHM) += touchpanel_algorithm.o
obj-$(CONFIG_TOUCHPANEL_SYNAPTICS) += Synaptics/
obj-$(CONFIG_TOUCHPANEL_SAMSUNG) += Samsung/
obj-y	+= touch.o
